name: Android Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.19.1'
        cache: 'npm'
        cache-dependency-path: 'Pitara Mobile Application Frontend/package-lock.json'
        
    - name: Install Dependencies
      working-directory: 'Pitara Mobile Application Frontend'
      run: |
        npm cache clean --force
        npm install
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
        
    - name: Build with Capacitor
      working-directory: 'Pitara Mobile Application Frontend'
      run: |
        npm run build
        npx cap sync android
        
    - name: Build Android APK
      working-directory: 'Pitara Mobile Application Frontend'
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: 'Pitara Mobile Application Frontend/android/app/build/outputs/apk/debug/*.apk'
        retention-days: 30 