name: Android APK Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Pitara Mobile Application Frontend/**'
      - '.github/workflows/android.yml'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Inject build-time environment variables for Google OAuth
      - name: Create environment file for Vite
        working-directory: Pitara Mobile Application Frontend
        run: |
          echo "VITE_GOOGLE_ANDROID_CLIENT_ID=1089697091920-0b2qntimau4d59chhqouu6i8j4u1e6oi.apps.googleusercontent.com" >> .env
          echo "VITE_GOOGLE_WEB_CLIENT_ID=1089697091920-98q7tp993p275ms9dbms9iodu5lh8rnp.apps.googleusercontent.com" >> .env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install project dependencies
        working-directory: Pitara Mobile Application Frontend
        run: npm install --no-audit --prefer-offline --legacy-peer-deps

      - name: Build web assets (Vite)
        working-directory: Pitara Mobile Application Frontend
        run: npm run build

      - name: Recreate Capacitor Android platform
        working-directory: Pitara Mobile Application Frontend
        run: |
          rm -rf android
          npx cap add android
          npx cap sync android

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build APK
        working-directory: Pitara Mobile Application Frontend/android
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pitara-universal-apk
          path: Pitara Mobile Application Frontend/android/app/build/outputs/apk/debug/app-debug.apk 