name: Android APK Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Pitara Mobile Application Frontend/**'
      - '.github/workflows/android.yml'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install project dependencies
        working-directory: Pitara Mobile Application Frontend
        run: npm ci

      - name: Build web assets (Vite)
        working-directory: Pitara Mobile Application Frontend
        run: npm run build

      - name: Initialize Capacitor Android project
        working-directory: Pitara Mobile Application Frontend
        run: |
          npx cap add android || echo 'android platform already exists'
          npx cap sync android

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build APK
        working-directory: Pitara Mobile Application Frontend/android
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pitara-universal-apk
          path: Pitara Mobile Application Frontend/android/app/build/outputs/apk/debug/app-debug.apk 