name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd "Pitara Mobile Application Frontend"
        npm install
        
    - name: Build Web App
      run: |
        cd "Pitara Mobile Application Frontend"
        npm run build
        
    - name: Sync Capacitor
      run: |
        cd "Pitara Mobile Application Frontend"
        npx cap sync android
        
    - name: Build Debug APK
      run: |
        cd "Pitara Mobile Application Frontend/android"
        chmod +x gradlew
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: Pitara Mobile Application Frontend/android/app/build/outputs/apk/debug/app-debug.apk 