// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://jdfnkvbfpvzddjtgiovj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZm5rdmJmcHZ6ZGRqdGdpb3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODE5OTcsImV4cCI6MjA2NTM1Nzk5N30.zHUA-ESeIWzsfEpkt6O7-nWOBLaBf8MCEQlUb2JcnOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detect if we are running in a native (non-web) Capacitor environment
const isNative = Capacitor?.getPlatform && Capacitor.getPlatform() !== 'web';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Mobile deep-link flows are handled manually, so we disable Supabase's default URL parsing
    detectSessionInUrl: false,
    // Persist and refresh sessions across app restarts
    persistSession: true,
    autoRefreshToken: true,
    // Ensure PKCE flow for native auth
    flowType: 'pkce'
  }
});